/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
// biome-ignore lint: disable
export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    'IconAntDesign:chromeOutlined': typeof import('~icons/ant-design/chrome-outlined')['default']
    'IconCarbon:moon': typeof import('~icons/carbon/moon')['default']
    'IconCarbon:sun': typeof import('~icons/carbon/sun')['default']
    'IconMdi:account': typeof import('~icons/mdi/account')['default']
    'IconMdi:github': typeof import('~icons/mdi/github')['default']
  }
}
